apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/Yuvalmendel10/todo-argocd.git
    targetRevision: HEAD
  destination:
    server: https://127.0.0.1:8081
    namespace: todo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

