apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: todo
  name: todo-service
spec:
  ports:
    - port: 444
      protocol: TCP
      targetPort: 5000
  selector:
    app: todo
status:
  loadBalancer: {}
