apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: todo
  name: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todo
    spec:
      containers:
        - image: yuvalmendel10/todo:41
          name: todo
          resources: {}
status: {}
